# docker-compose.yml
version: '3.8' # 建议使用最新版本，例如 3.8

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8086:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      # 从 .env 文件中获取敏感信息，确保 .env 文件与 docker-compose.yml 在同一目录下
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/telegram-favorites?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - TELEGRAM_SESSION_ENCRYPTION_KEY=${TELEGRAM_SESSION_ENCRYPTION_KEY} # 关键：加密密钥
      - NODE_ENV=${NODE_ENV:-development} # 默认开发环境，生产环境请设置为 production
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost:8086} # 生产环境请设置为您的前端域名
      - PORT=3077
    ports:
      - "3077:3077"
    volumes:
      - backend-uploads:/app/uploads # 持久化后端上传文件目录
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME} # 引用 .env 中的用户名
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD} # 引用 .env 中的密码
      - MONGO_INITDB_DATABASE=telegram-favorites
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
  backend-uploads: # 定义后端上传文件目录的具名卷